M48
; DRILL file {KiCad 8.0.0} date 2025-06-12T16:21:02-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-12T16:21:02-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X102.108Y-46.939
X102.108Y-95.199
X216.408Y-46.939
X216.408Y-95.199
M30
